@startuml db

package com.google.gson #EEEEEE{}

package model.gerarchia #EEEEEE{}

package model.scambio #EEEEEE{}

package model.offerta #EEEEEE{}

package "db" #DDDDDD{
    
    class JsonUtil{
        +{static} writeGerarchia(gerarchia: Gerarchia): void
        -{static} createListOfFile(directory: String): List<Path>
        +{static} readGerarchia(): List<Gerarchia>
        +{static} checkNomeGerarchiaRipetuto(nome: String): boolean
        +{static} writeScambio(scambio: Scambio): void
        +{static} readScambio(): List<Scambio>
        +{static} writeOfferta(offerta: Offerta): void
        +{static} readOffertaByCategoria(nomeCategoria: String): List<Offerta>
        +{static} readOffertaByAutore(autore: String): List<Offerta>
    }

    JsonUtil -up..> com.google.gson: use
    JsonUtil -up..> model.gerarchia: use
    JsonUtil -up..> model.scambio: use
    JsonUtil -up..> model.offerta: use

}
note right of JsonUtil
nuovi metodi: 
    - writeOfferta
    - readOffertaByCategoria
    - readOffertaByAutore
end note




@enduml