@startuml db

package com.google.gson #EEEEEE{}

package model.gerarchia #EEEEEE{}

package model.scambio #EEEEEE{}

package model.offerta #EEEEEE{}

package model.baratto #EEEEEE{}

package "db" #DDDDDD{
    
    class JsonUtil{
        +{static} writeGerarchia(gerarchia: Gerarchia): void
        -{static} createListOfFile(directory: String): List<Path>
        +{static} readGerarchia(): List<Gerarchia>
        +{static} checkNomeGerarchiaRipetuto(nome: String): boolean
        +{static} writeScambio(scambio: Scambio): void
        +{static} readScambio(): List<Scambio>
        +{static} writeOfferta(offerta: Offerta): void
        +{static} readOffertaByCategoria(nomeCategoria: String): List<Offerta>
        +{static} readOffertaByAutore(autore: String): List<Offerta>
        +{static} readOffertaByAutoreAndState(autore: String, stat: StatoOfferta): List<Offerta>
        +{static} readOfferteAperteByCategoria(autore: String, categoria: Categoria): List<Offerta>
        +{static} writeBaratto(baratto: Baratto): void
        +{static} readBarattoByUtente(utente: String): List<Baratto>
        +{static} readBarattoInScambio(utente: String): List<Baratto>
        +{static} readBarattoByOfferta(offerta: Offerta): List<Baratto>
        +{static} deleteBaratto(baratto: Baratto): void
        +{static} eliminaBarattiScaduti(): boolean

    }

    JsonUtil -up..> com.google.gson: use
    JsonUtil -up..> model.gerarchia: use
    JsonUtil -up..> model.scambio: use
    JsonUtil -up..> model.offerta: use
    JsonUtil -up..> model.baratto: use

}
note right of JsonUtil
nuovi metodi: 
    - readOffertaByAutoreAndState
    - readOfferteAperteByCategoria
    - writeBaratto
    - readBarattoByUtente
    - readBarattoInScambio
    - readBarattoByOfferta
    - deleteBaratto
    - eliminaBarattiScaduti
end note




@enduml