@startuml main
class Administrator {
    +{static} main(args: String[]): void
    +{static} getNewPassword (pwSize: int): String
    +{static} writePasswordToFile (user: String, pass: String): void

}

class Main {
    +{static} main(args: String[]): void
}


Main o--> controller.OptionList
Main o--> utility.MyMenu

Administrator ..> utility.DbConnect: use

@enduml