@startuml main

class MainConfiguratore {
    +{static} main(args: String[]): void
}

class MainFruitore {
    +{static} main(args: String[]): void
}


MainConfiguratore o--> controller.OptionList
MainConfiguratore o--> db.MyMenu

MainFruitore o--> controller.OptionList
MainFruitore o--> db.MyMenu


@enduml