@startuml
interface "Controller" as controller
class "ControllerConfiguratore" as contrConfig
class "ControllerFruitore" as contrFruitore

contrConfig .u.> controller
contrFruitore .u.> controller
controller "1" <-l* "1" Main

@enduml